//! This module contains the configuration for the libos crate,
//! which is generated by the build script automatically, see `shim_config.rs`.

/// This mod contains macros to include files with specific alignment.
/// The `include_bytes_align_as!` macro allows you to include a file as a byte array
/// with a specific alignment type. This is useful for including binary files
/// that need to be aligned to a certain byte boundary.
///
/// Why we need this？
///
/// In crate `zero`, which is a dependency of `xmas-elf`, the `read` function will
/// check the alignment of the data. If the data is not aligned, it will panic.
///
/// `assert!((addr & (mem::align_of::<T>() - 1)) == 0);`
///
/// Reference: [Can i conveniently compile bytes into a Rust program with a specific alignment?](https://users.rust-lang.org/t/can-i-conveniently-compile-bytes-into-a-rust-program-with-a-specific-alignment/24049/2)
#[macro_use]
mod macros {
    #[repr(C)] // guarantee 'bytes' comes after '_align'
    pub struct AlignedAs<Align, Bytes: ?Sized> {
        pub _align: [Align; 0],
        pub bytes: Bytes,
    }

    macro_rules! include_bytes_align_as {
        ($align_ty:ty, $path:literal) => {{
            // const block expression to encapsulate the static
            use $crate::libos::config::macros::AlignedAs;

            // this assignment is made possible by CoerceUnsized
            static ALIGNED: &AlignedAs<$align_ty, [u8]> = &AlignedAs {
                _align: [],
                bytes: *include_bytes!($path),
            };

            &ALIGNED.bytes
        }};
    }
}

include!(concat!(env!("OUT_DIR"), "/shim_configs.rs"));

pub const SHIM_PHYS_VIRT_OFFSET: usize = SHIM_KERNEL_BASE_VADDR - SHIM_KERNEL_BASE_PADDR;
