cd crates/arceos && git checkout rk3588_jd4_qemu
cd ../arm_vcpu && git checkout inject_interrupt_vgicv3_ivc
cd ../arm_vgic && git checkout inject_interrupt_vgicv3
cd ../axaddrspace && git checkout 4_level_paging
cd ../axdevice && git checkout ivc
cd ../axdevice_crates && git checkout inject_interrupt_ivc
cd ../axhvc && git checkout ivc
cd ../axvcpu && git checkout inject_interrupt_vgicv3_ivc
cd ../axvm && git checkout ivc