# Stack size of each task.
task-stack-size = 0x40000   # uint

# Number of timer ticks per second (Hz). A timer tick may contain several timer
# interrupts.

# WORKAROUND: To provide correct `CNTFRQ_EL0` value to the guest in aarch64.
ticks-per-sec = 1000         # uint

# Number of CPUs
smp = 1                     # uint
