# Vm base info configs
#
[base]
# Guest vm id.
id = 2
# Guest vm name.
name = "arceos"
# Virtualization type.
vm_type = 1
# The number of virtual CPUs.
cpu_num = 1
# Guest vm physical cpu sets.
phys_cpu_sets = [4]

#
# Vm kernel configs
#
[kernel]
# The entry point of the kernel image.
entry_point = 0x1_0048_0000
# The load address of the kernel image.
kernel_load_addr = 0x1_0048_0000
# The load address of the device tree blob (DTB).
dtb_load_addr = 0x1_1000_0000
# The location of image: "memory" | "fs".
# Load from memory
image_location = "memory"
# The file path of the kernel image.
kernel_path = "gicv3_tester_aarch64-rk3588j-guest.bin"
# The file path of the device tree blob (DTB).
dtb_path = "aio-rk3588-jd4-vm2.dtb"
# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = []

#
# Device specifications
#
[devices]
# Emu_devices.
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig.
emu_devices = []

# Pass-through devices.
# Name Base-Ipa Base-Pa Length Alloc-Irq.
passthrough_devices = [
    ["uart@feb40000", 0xfeb4_0000, 0xfeb4_0000, 0x1000, 0x1],
    ["uart@feb50000", 0xfeb5_0000, 0xfeb4_0000, 0x1000, 0x1],
]
