# Vm base info configs
#
[base]
# Guest vm id.
id = 1
# Guest vm name.
name = "arceos"
# Virtualization type.
vm_type = 1
# The number of virtual CPUs.
cpu_num = 1
# Guest vm physical cpu sets.
phys_cpu_sets = [1]

#
# Vm kernel configs
#
[kernel]
# The entry point of the kernel image.
entry_point = 0x20_0000
# The location of image: "memory" | "fs".
# Load from file system.
image_location = "memory"
# The file path of the BIOS image.
bios_path = "/home/debin/code/axvisor/vmm0626/axvm-bios.bin"
# The load address of the BIOS image.
bios_load_addr = 0x8000
# The file path of the kernel image.
# kernel_path = "/home/debin/code/axvisor/vmm0626/arceos/examples/shell/shell_x86_64-qemu-q35.bin"
kernel_path = "/home/debin/code/axvisor/vmm0626/arceos/examples/helloworld/helloworld_x86_64-qemu-q35.bin"
# The load address of the kernel image.
kernel_load_addr = 0x20_0000

## The file path of the ramdisk image.
# ramdisk_path = ""
## The load address of the ramdisk image.
# ramdisk_load_addr = 0
## The path of the disk image.
# disk_path = "disk.img"

# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = [
    [0x0000_0000, 0x100_0000, 0x7, 0], # Low RAM		16M	0b111
]

#
# Device specifications
#
[devices]
# Emu_devices.
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig.
emu_devices = [
    ["virtio_mmio", 0xfd000000, 0x1000, 0x1, 3, [0]]
]


# Pass-through devices.
# Name Base-Ipa Base-Pa Length Alloc-Irq.
passthrough_devices = [
    [
        "IO APIC",
        0xfec0_0000,
        0xfec0_0000,
        0x1000,
        0x1,
    ],
    [
        "Local APIC",
        0xfee0_0000,
        0xfee0_0000,
        0x1000,
        0x1,
    ],
    [
        "HPET",
        0xfed0_0000,
        0xfed0_0000,
        0x1000,
        0x1,
    ],
]